import { Menu, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { useLocation } from 'react-router-dom'
import { NAVIGATION } from '../data/constants'
import Button from './Button'
import Logo from './Logo'

export default function Navbar() { const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false); const [progress, setProgress] = useState(0); const { pathname } = useLocation(); useEffect(() => { const listener = () => { setScrolled(window.scrollY > 20); const height = document.documentElement.scrollHeight - window.innerHeight; setProgress(height > 0 ? (window.scrollY / height) * 100 : 0) }; listener(); window.addEventListener('scroll', listener, { passive: true }); return () => window.removeEventListener('scroll', listener) }, []); return <header className={`fixed inset-x-0 top-0 z-50 transition-all duration-300 ${scrolled ? 'border-b border-white/10 bg-ink/85 py-3 backdrop-blur-xl' : 'py-5'}`}><motion.div className="absolute bottom-0 left-0 h-px bg-gradient-to-r from-indigo via-violet to-cyan" animate={{ width: `${progress}%` }} transition={{ duration: .12 }} /><div className="section-shell flex items-center justify-between"><a href="/" aria-label="Kodnexa home"><Logo /></a><nav aria-label="Main navigation" className="hidden items-center gap-7 lg:flex">{NAVIGATION.map(({ label, path }) => <a key={path} href={path} aria-current={pathname === path ? 'page' : undefined} className={`text-sm font-medium transition hover:text-white ${pathname === path ? 'text-white' : 'text-slate-400'}`}>{label}</a>)}</nav><div className="hidden lg:block"><Button href="/contact" className="px-4 py-2.5">Book a meeting</Button></div><button onClick={() => setOpen(!open)} aria-label="Toggle menu" className="grid h-10 w-10 place-items-center rounded-lg border border-white/10 text-white lg:hidden">{open ? <X /> : <Menu />}</button></div><AnimatePresence>{open && <motion.nav aria-label="Mobile navigation" initial={{ opacity: 0, y: -12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -12 }} className="section-shell mt-3 lg:hidden"><div className="glass rounded-2xl p-4"><a href="/" onClick={() => setOpen(false)} className="mb-2 block px-4"><Logo /></a>{NAVIGATION.map(({ label, path }) => <a onClick={() => setOpen(false)} key={path} href={path} aria-current={pathname === path ? 'page' : undefined} className={`block rounded-lg px-4 py-3 text-sm font-medium hover:bg-white/5 hover:text-white ${pathname === path ? 'text-white' : 'text-slate-300'}`}>{label}</a>)}<Button href="/contact" className="mt-2 w-full">Book a meeting</Button></div></motion.nav>}</AnimatePresence></header> }
