import { useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import { ArrowLeft, CheckCircle2, X } from 'lucide-react'
import Button from './Button'

const List = ({ title, items }) => items?.length ? <div><h3 className="text-xs font-semibold uppercase tracking-[.16em] text-slate-500">{title}</h3><ul className="mt-3 grid gap-2 sm:grid-cols-2">{items.map(item => <li key={item} className="flex gap-2 text-sm leading-6 text-slate-300"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-cyan" />{item}</li>)}</ul></div> : null

function WaitlistForm({ product, onBack }) {
  const [message, setMessage] = useState('')
  const submit = event => { event.preventDefault(); if (event.currentTarget.checkValidity()) setMessage('Waitlist submission is ready for a future backend integration. Your details have not been stored yet.') }
  return <div className="mt-8 border-t border-white/10 pt-7"><button type="button" onClick={onBack} className="inline-flex items-center gap-2 text-sm font-semibold text-indigo-300 hover:text-white"><ArrowLeft className="h-4 w-4" />Back to product</button><h3 className="mt-5 font-display text-2xl text-white">Join the waitlist</h3><p className="mt-2 text-sm leading-6 text-slate-400">Be among the first to hear when {product.name} is ready.</p><form onSubmit={submit} className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm text-slate-300">Name<input required name="name" autoComplete="name" className="mt-2 w-full rounded-xl border border-white/10 bg-white/[.04] px-4 py-3 text-white outline-none focus:border-cyan/60" /></label><label className="text-sm text-slate-300">Work Email<input required type="email" name="email" autoComplete="email" className="mt-2 w-full rounded-xl border border-white/10 bg-white/[.04] px-4 py-3 text-white outline-none focus:border-cyan/60" /></label><label className="text-sm text-slate-300">Company <span className="text-slate-500">(optional)</span><input name="company" autoComplete="organization" className="mt-2 w-full rounded-xl border border-white/10 bg-white/[.04] px-4 py-3 text-white outline-none focus:border-cyan/60" /></label><label className="text-sm text-slate-300">Product interested in<input readOnly value={product.name} className="mt-2 w-full cursor-default rounded-xl border border-white/10 bg-white/[.04] px-4 py-3 text-slate-300 outline-none" /></label><div className="sm:col-span-2"><Button type="submit">Notify Me</Button></div></form>{message && <p role="status" className="mt-4 rounded-xl border border-amber-300/20 bg-amber-300/10 px-4 py-3 text-sm leading-6 text-amber-100">{message}</p>}</div>
}

export default function ProductDetails({ product, onClose }) {
  const [waitlist, setWaitlist] = useState(false)
  useEffect(() => { const close = event => event.key === 'Escape' && onClose(); window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close) }, [onClose])
  if (!product) return null
  const Icon = product.icon
  return <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onMouseDown={event => event.target === event.currentTarget && onClose()} className="fixed inset-0 z-[100] flex items-end bg-ink/85 p-3 backdrop-blur-sm sm:items-center sm:justify-center" role="dialog" aria-modal="true" aria-label={`${product.name} details`}><motion.article initial={{ y: 24, scale: .98 }} animate={{ y: 0, scale: 1 }} exit={{ y: 24, scale: .98 }} className="max-h-[94vh] w-full max-w-4xl overflow-y-auto rounded-3xl border border-white/10 bg-panel p-6 shadow-2xl sm:p-9"><div className="flex items-start justify-between gap-5"><div className="flex gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-indigo/15 text-indigo-300"><Icon className="h-6 w-6" /></span><div><span className="rounded-full border border-cyan/20 bg-cyan/10 px-2.5 py-1 text-[10px] font-bold tracking-[.14em] text-cyan-200">COMING SOON</span><p className="mt-3 text-xs font-semibold uppercase tracking-[.16em] text-cyan">{product.category}</p></div></div><button type="button" onClick={onClose} className="grid h-9 w-9 shrink-0 place-items-center rounded-lg text-slate-400 hover:bg-white/5 hover:text-white" aria-label="Close product details"><X className="h-5 w-5" /></button></div><h2 className="mt-6 font-display text-3xl text-white sm:text-4xl">{product.name}</h2><p className="mt-2 font-display text-lg text-indigo-200">{product.tagline}</p><p className="mt-5 max-w-3xl leading-7 text-slate-400">{product.description}</p>{waitlist ? <WaitlistForm product={product} onBack={() => setWaitlist(false)} /> : <><div className="mt-9 border-t border-white/10 pt-7"><h3 className="text-xs font-semibold uppercase tracking-[.16em] text-slate-500">How it works</h3><ol className="mt-4 grid gap-3 sm:grid-cols-2">{product.steps.map((step, index) => <li key={step} className="flex gap-3 text-sm leading-6 text-slate-300"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-indigo/15 text-xs font-bold text-indigo-200">{index + 1}</span>{step}</li>)}</ol></div><div className="mt-9 grid gap-8 border-t border-white/10 pt-7"><List title="Features" items={product.features} /><List title={product.useCases ? 'Use cases' : 'Ideal for'} items={product.useCases || product.idealFor} />{product.example && <div><h3 className="text-xs font-semibold uppercase tracking-[.16em] text-slate-500">Example</h3><p className="mt-3 text-sm leading-7 text-slate-300">{product.example}</p></div>}{product.note && <div><h3 className="text-xs font-semibold uppercase tracking-[.16em] text-slate-500">Technology & integration note</h3><p className="mt-3 text-sm leading-7 text-slate-300">{product.note}</p></div>}</div><Button onClick={() => setWaitlist(true)} className="mt-9">Join the Waitlist</Button></>}</motion.article></motion.div>
}
